spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/basicStore?useUnicode=true&characterEncoding=utf8
      username: DQ
      password: Test202@
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor